package com.cupidapp.live.base.sensorslog;

import com.huawei.hms.framework.network.grs.GrsBaseInfo;
import kotlin.d;
import kotlin.jvm.internal.s;
import org.jetbrains.annotations.NotNull;

/* compiled from: SensorPosition.kt */
@d
/* loaded from: C:\Users\35037\Desktop\fankahook\2\class2.dex */
public enum SensorPosition {
    Match("MATCH"),
    Nearby("NEARBY"),
    Accessibility("ASSISTIVE_FUNCTION"),
    NearbyCoverCard("NEARBY_COVER_CARD"),
    NotVipNearby("NOT_VIP_NEARBY"),
    MatchSuccess("MATCH_SUCCESS"),
    MatchFilter("MATCH_FILTER"),
    RcmdFilterGuide("RECOMMEND_FILTER_GUIDE"),
    ContactFilter("CONTACTS_FILTER"),
    Search("SEARCH"),
    PreviewLiveShow("PREVIEW_LIVE_SHOW"),
    LiveShow("LIVE_SHOW"),
    LiveHot("LIVE_HOT"),
    LiveNearby("LIVE_NEARBY"),
    LiveRecommend("LIVE_RECOMMEND"),
    LiveFollow("LIVE_FOLLOW"),
    LiveConfigurable("LIVE_CONFIGURABLE"),
    AnchorLiveShowRoom("ANCHOR_LIVE_ROOM"),
    LiveShowRoom("LIVE_SHOW_ROOM"),
    MiniProfile("MINI_PROFILE"),
    LiveContent("LIVE_CONTENT"),
    LivePageCutCover("LIVE_PAGE_CUT_COVER"),
    Message("MESSAGE"),
    Contacts("CONTACTS"),
    MessageDetail("MESSAGE_DETAIL"),
    PostLimit("TIME_LIMIT_FEED_DETAIL"),
    PostLimitPrivate("PRIVATE_ALBUM_TIME_LIMIT"),
    PostLimitEdit("TIME_LIMIT_FEED_EDIT"),
    Feed("FEED"),
    FeedDetail("FEED_DETAIL"),
    RecommendFeed("RECOMMEND_FEED"),
    Hashtag("HASHTAG"),
    HashtagHot("HASHTAG_HOT"),
    HashtagNew("HASHTAG_NEW"),
    HashtagList("HASHTAG_LIST"),
    HashtagSelect("HASHTAG_SELECT"),
    PostStream("POST_STREAM"),
    Comment("COMMENT"),
    Notify("NOTIFY"),
    NotifyAloha("NOTIFY_ALOHA"),
    NotifyGetLike("NOTIFY_GET_LIKE"),
    NotifyMention("NOTIFY_MENTION"),
    Welcome("WELCOME"),
    Login("LOGIN"),
    VerifySMSLogin("VERIFY_SMS_LOGIN"),
    PasswordLogin("PASSWORD_LOGIN"),
    OnePassLogin("ONE_PASS_LOGIN"),
    RegisterAddAvatar("UPLOAD_AVATAR"),
    RegisterImageCrop("REGISTER_IMAGE_CROP"),
    Setting("PROFILE_TAB"),
    Profile("PROFILE"),
    MyProfile("MY_PROFILE"),
    EditAvatar("EDIT_AVATAR"),
    MyAloha("MY_ALOHA"),
    MyAlohaGet("MY_ALOHA_GET"),
    PraisedFeed("LIKED_FEED"),
    PrivacySetting("PRIVACY_SETTING"),
    PersonalizationOptions("PERSONALIZATION_OPTIONS"),
    EditProfile("EDIT_PROFILE"),
    BlackListPage("BLACKLIST_PAGE"),
    MyVisitors("MY_VISITORS"),
    MyVisitorsSubPage("MY_VISITORS_SUBPAGE"),
    HideFootmark("HIDE_FOOT_MARK"),
    ImageEditor("IMAGE_EDITOR"),
    Web("WEB"),
    AccountSecurity("ACCOUNT_SECURITY"),
    ChangePasswordVerify("CHANGE_PASSWORD_VERIFY"),
    ChangePhoneNumber("CHANGE_PHONE_NUMBER"),
    ChangePasswordInputNewPassword("CHANGE_PASSWORD_INPUT_NEW_PASSWORD"),
    ChangePasswordInputVerifyCode("CHANGE_PASSWORD_INPUT_VERIFY_CODE"),
    LogoutSettingPassword("LOGOUT_SETTING_PASSWORD"),
    BlockedUserList("BLOCKED_USER_LIST"),
    Splash("SPLASH_AD"),
    NearMatch("NEARBY_MATCH"),
    PrivateFeed("PRIVATE_ALBUM"),
    Push("PUSH"),
    StoryLabel("STORY_LABEL"),
    ReadFeed("READ_FEED"),
    EditFeed("EDIT_FEED"),
    SnapImage("SNAP_IMAGE"),
    NewMsgNotice("NEW_MSG_NOTICE"),
    RecommendFeedEnter(""),
    Focus("SPECIAL_ATTENTION"),
    CloseFriend("CLOSE_FRIENDS"),
    FeedPublishRange("POST_PERMISSION_SETTING"),
    OpenPushGuide("OPEN_PUSH_GUIDE"),
    RecommendedChat("RECOMMENDED_CHAT"),
    ChatRoom("CHAT_ROOM"),
    ChatStatus("CHAT_STATUS"),
    MaskParty("MASK_PARTY"),
    FindPageCategory("FIND_PAGE_CATEGORY"),
    Unknown(GrsBaseInfo.CountryCodeSource.UNKNOWN),
    DynPosition(GrsBaseInfo.CountryCodeSource.UNKNOWN),
    NickNameFill("NICKNAME_FILL"),
    BirthdayFill("BIRTHDAY_FILL"),
    NewTaskReward("NEW_TASK_REWARD"),
    PersonalIcon("PERSONAL_ICON"),
    DailyHeart("DAILY_HEART"),
    HeartUnlock("DAILY_HEART_UNLOCK"),
    SwitchAccount("SWITCH_ACCOUNT"),
    VoiceParty("VOICE_PARTY"),
    VoiceRoom("VOICE_ROOM"),
    LiveEnd("LIVE_END"),
    PropCard("PROP_CARD"),
    LiveSetting("LIVE_SETTING"),
    ReceivedPraise("RECEIVED_PRAISE"),
    SendPraise("SEND_PRAISE"),
    PraiseDetail("PRAISE_DETAIL"),
    SuperExposure("SUPER_EXPOSURE"),
    CONTACT_MANAGEMENT("CONTACT_MANAGEMENT"),
    ALOHA_NOT_MATCH("ALOHA_NOT_MATCH"),
    ALOHA_NOT_MATCH_BAN("ALOHA_NOT_MATCH_BAN"),
    PERSONAL_SETTING("PERSONAL_SETTING"),
    INTELLIGENT_FILTER("INTELLIGENT_FILTER"),
    MenuSetting("SETTING"),
    CancelAloha("CANCEL_ALOHA_LIST"),
    ClubList("CLUB_LIST"),
    ClubActivity("CLUB_ACTIVITY"),
    ClubRank("CLUB_RANK"),
    ClubGroupChat("CLUB_GROUP_CHAT"),
    ClubGroupActivity("CLUB_GROUP_ACTIVITY"),
    RainbowRecommend("RAINBOW_A_PLUS_RECOMMEND"),
    AiIdentify("AI_FACE_IDENTITY"),
    AiIdentifyResult("AI_FACE_IDENTITY_RESULT"),
    FeedActivity("FEED_ACTIVITY"),
    PREVIEW_CONSULT_SHOW("PREVIEW_CONSULT_SHOW"),
    CONSULT_ROOM("CONSULT_ROOM"),
    ConsultList("CONSULT_LIST"),
    ConsultPageCutCover("CONSULT_PAGE_CUT_COVER"),
    UnlockNearBy("UNLOCK_NEARBY_DETAIL"),
    MBTI_SETTING("MBTI_SETTING"),
    Startup("START_UP"),
    Map("Map"),
    Flutter("Flutter"),
    TravelMap("TRAVEL_MODE_SET_MAP"),
    NewUserGuideIntro("MATCH_NEW_USER_FUNCTION_GUIDE"),
    RoamingFlutter("ROAMING");


    @NotNull
    private String value;

    SensorPosition(String str) {
        this.value = str;
    }

    @NotNull
    public final String getValue() {
        return this.value;
    }

    public final void setValue(@NotNull String str) {
        s.i(str, "<set-?>");
        this.value = str;
    }
}
